name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > types.gen.ts
          if git diff --ignore-space-at-eol --exit-code types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Debugging Info
        run: |
            ls -la         # List all files in the current directory for debugging
            git status     # Show the current Git status
            supabase gen types typescript --local > types.gen.ts
            ls -la         # List files again to check if types.gen.ts is generated
            git status     # Show Git status after generating types